// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: university.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_university_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_university_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_university_proto_rawDescGZIP(), []int{0}
}

type UniversityMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Website       string                 `protobuf:"bytes,5,opt,name=website,proto3" json:"website,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UniversityMessage) Reset() {
	*x = UniversityMessage{}
	mi := &file_university_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniversityMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniversityMessage) ProtoMessage() {}

func (x *UniversityMessage) ProtoReflect() protoreflect.Message {
	mi := &file_university_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniversityMessage.ProtoReflect.Descriptor instead.
func (*UniversityMessage) Descriptor() ([]byte, []int) {
	return file_university_proto_rawDescGZIP(), []int{1}
}

func (x *UniversityMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UniversityMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UniversityMessage) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UniversityMessage) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *UniversityMessage) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *UniversityMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UniversityMessage) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateUniversityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Website       string                 `protobuf:"bytes,4,opt,name=website,proto3" json:"website,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUniversityRequest) Reset() {
	*x = CreateUniversityRequest{}
	mi := &file_university_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUniversityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUniversityRequest) ProtoMessage() {}

func (x *CreateUniversityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_university_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUniversityRequest.ProtoReflect.Descriptor instead.
func (*CreateUniversityRequest) Descriptor() ([]byte, []int) {
	return file_university_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUniversityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUniversityRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateUniversityRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateUniversityRequest) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

type GetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDRequest) Reset() {
	*x = GetByIDRequest{}
	mi := &file_university_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDRequest) ProtoMessage() {}

func (x *GetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_university_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return file_university_proto_rawDescGZIP(), []int{3}
}

func (x *GetByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateUniversityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Website       string                 `protobuf:"bytes,5,opt,name=website,proto3" json:"website,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUniversityRequest) Reset() {
	*x = UpdateUniversityRequest{}
	mi := &file_university_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUniversityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUniversityRequest) ProtoMessage() {}

func (x *UpdateUniversityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_university_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUniversityRequest.ProtoReflect.Descriptor instead.
func (*UpdateUniversityRequest) Descriptor() ([]byte, []int) {
	return file_university_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUniversityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUniversityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUniversityRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateUniversityRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *UpdateUniversityRequest) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

type DeleteUniversityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUniversityRequest) Reset() {
	*x = DeleteUniversityRequest{}
	mi := &file_university_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUniversityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUniversityRequest) ProtoMessage() {}

func (x *DeleteUniversityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_university_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUniversityRequest.ProtoReflect.Descriptor instead.
func (*DeleteUniversityRequest) Descriptor() ([]byte, []int) {
	return file_university_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteUniversityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UniversitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Universities  []*UniversityMessage   `protobuf:"bytes,1,rep,name=universities,proto3" json:"universities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UniversitiesResponse) Reset() {
	*x = UniversitiesResponse{}
	mi := &file_university_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniversitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniversitiesResponse) ProtoMessage() {}

func (x *UniversitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_university_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniversitiesResponse.ProtoReflect.Descriptor instead.
func (*UniversitiesResponse) Descriptor() ([]byte, []int) {
	return file_university_proto_rawDescGZIP(), []int{6}
}

func (x *UniversitiesResponse) GetUniversities() []*UniversityMessage {
	if x != nil {
		return x.Universities
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_university_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_university_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_university_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_university_proto protoreflect.FileDescriptor

const file_university_proto_rawDesc = "" +
	"\n" +
	"\x10university.proto\x12\n" +
	"university\"\a\n" +
	"\x05Empty\"\xbd\x01\n" +
	"\x11UniversityMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x18\n" +
	"\awebsite\x18\x05 \x01(\tR\awebsite\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"u\n" +
	"\x17CreateUniversityRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x18\n" +
	"\awebsite\x18\x04 \x01(\tR\awebsite\" \n" +
	"\x0eGetByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x85\x01\n" +
	"\x17UpdateUniversityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x18\n" +
	"\awebsite\x18\x05 \x01(\tR\awebsite\")\n" +
	"\x17DeleteUniversityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Y\n" +
	"\x14UniversitiesResponse\x12A\n" +
	"\funiversities\x18\x01 \x03(\v2\x1d.university.UniversityMessageR\funiversities\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xb3\x03\n" +
	"\x11UniversityService\x12V\n" +
	"\x10CreateUniversity\x12#.university.CreateUniversityRequest\x1a\x1d.university.UniversityMessage\x12I\n" +
	"\x12GetAllUniversities\x12\x11.university.Empty\x1a .university.UniversitiesResponse\x12N\n" +
	"\x11GetUniversityByID\x12\x1a.university.GetByIDRequest\x1a\x1d.university.UniversityMessage\x12V\n" +
	"\x10UpdateUniversity\x12#.university.UpdateUniversityRequest\x1a\x1d.university.UniversityMessage\x12S\n" +
	"\x10DeleteUniversity\x12#.university.DeleteUniversityRequest\x1a\x1a.university.DeleteResponseB(Z&university-service/internal/grpc/pb;pbb\x06proto3"

var (
	file_university_proto_rawDescOnce sync.Once
	file_university_proto_rawDescData []byte
)

func file_university_proto_rawDescGZIP() []byte {
	file_university_proto_rawDescOnce.Do(func() {
		file_university_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_university_proto_rawDesc), len(file_university_proto_rawDesc)))
	})
	return file_university_proto_rawDescData
}

var file_university_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_university_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: university.Empty
	(*UniversityMessage)(nil),       // 1: university.UniversityMessage
	(*CreateUniversityRequest)(nil), // 2: university.CreateUniversityRequest
	(*GetByIDRequest)(nil),          // 3: university.GetByIDRequest
	(*UpdateUniversityRequest)(nil), // 4: university.UpdateUniversityRequest
	(*DeleteUniversityRequest)(nil), // 5: university.DeleteUniversityRequest
	(*UniversitiesResponse)(nil),    // 6: university.UniversitiesResponse
	(*DeleteResponse)(nil),          // 7: university.DeleteResponse
}
var file_university_proto_depIdxs = []int32{
	1, // 0: university.UniversitiesResponse.universities:type_name -> university.UniversityMessage
	2, // 1: university.UniversityService.CreateUniversity:input_type -> university.CreateUniversityRequest
	0, // 2: university.UniversityService.GetAllUniversities:input_type -> university.Empty
	3, // 3: university.UniversityService.GetUniversityByID:input_type -> university.GetByIDRequest
	4, // 4: university.UniversityService.UpdateUniversity:input_type -> university.UpdateUniversityRequest
	5, // 5: university.UniversityService.DeleteUniversity:input_type -> university.DeleteUniversityRequest
	1, // 6: university.UniversityService.CreateUniversity:output_type -> university.UniversityMessage
	6, // 7: university.UniversityService.GetAllUniversities:output_type -> university.UniversitiesResponse
	1, // 8: university.UniversityService.GetUniversityByID:output_type -> university.UniversityMessage
	1, // 9: university.UniversityService.UpdateUniversity:output_type -> university.UniversityMessage
	7, // 10: university.UniversityService.DeleteUniversity:output_type -> university.DeleteResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_university_proto_init() }
func file_university_proto_init() {
	if File_university_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_university_proto_rawDesc), len(file_university_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_university_proto_goTypes,
		DependencyIndexes: file_university_proto_depIdxs,
		MessageInfos:      file_university_proto_msgTypes,
	}.Build()
	File_university_proto = out.File
	file_university_proto_goTypes = nil
	file_university_proto_depIdxs = nil
}
