// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: application.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApplicationService_Apply_FullMethodName                  = "/application.ApplicationService/Apply"
	ApplicationService_GetMyApplications_FullMethodName      = "/application.ApplicationService/GetMyApplications"
	ApplicationService_GetVacancyApplications_FullMethodName = "/application.ApplicationService/GetVacancyApplications"
	ApplicationService_UpdateStatus_FullMethodName           = "/application.ApplicationService/UpdateStatus"
	ApplicationService_Withdraw_FullMethodName               = "/application.ApplicationService/Withdraw"
	ApplicationService_GetApplicationStats_FullMethodName    = "/application.ApplicationService/GetApplicationStats"
)

// ApplicationServiceClient is the client API for ApplicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApplicationServiceClient interface {
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplicationMessage, error)
	GetMyApplications(ctx context.Context, in *GetMyApplicationsRequest, opts ...grpc.CallOption) (*ApplicationsResponse, error)
	GetVacancyApplications(ctx context.Context, in *GetVacancyApplicationsRequest, opts ...grpc.CallOption) (*ApplicationsResponse, error)
	UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*ApplicationMessage, error)
	Withdraw(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	GetApplicationStats(ctx context.Context, in *AppStatsEmpty, opts ...grpc.CallOption) (*ApplicationStatsResponse, error)
}

type applicationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApplicationServiceClient(cc grpc.ClientConnInterface) ApplicationServiceClient {
	return &applicationServiceClient{cc}
}

func (c *applicationServiceClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplicationMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationMessage)
	err := c.cc.Invoke(ctx, ApplicationService_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) GetMyApplications(ctx context.Context, in *GetMyApplicationsRequest, opts ...grpc.CallOption) (*ApplicationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationsResponse)
	err := c.cc.Invoke(ctx, ApplicationService_GetMyApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) GetVacancyApplications(ctx context.Context, in *GetVacancyApplicationsRequest, opts ...grpc.CallOption) (*ApplicationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationsResponse)
	err := c.cc.Invoke(ctx, ApplicationService_GetVacancyApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*ApplicationMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationMessage)
	err := c.cc.Invoke(ctx, ApplicationService_UpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) Withdraw(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, ApplicationService_Withdraw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) GetApplicationStats(ctx context.Context, in *AppStatsEmpty, opts ...grpc.CallOption) (*ApplicationStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationStatsResponse)
	err := c.cc.Invoke(ctx, ApplicationService_GetApplicationStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplicationServiceServer is the server API for ApplicationService service.
// All implementations must embed UnimplementedApplicationServiceServer
// for forward compatibility.
type ApplicationServiceServer interface {
	Apply(context.Context, *ApplyRequest) (*ApplicationMessage, error)
	GetMyApplications(context.Context, *GetMyApplicationsRequest) (*ApplicationsResponse, error)
	GetVacancyApplications(context.Context, *GetVacancyApplicationsRequest) (*ApplicationsResponse, error)
	UpdateStatus(context.Context, *UpdateStatusRequest) (*ApplicationMessage, error)
	Withdraw(context.Context, *WithdrawRequest) (*DeleteResponse, error)
	GetApplicationStats(context.Context, *AppStatsEmpty) (*ApplicationStatsResponse, error)
	mustEmbedUnimplementedApplicationServiceServer()
}

// UnimplementedApplicationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApplicationServiceServer struct{}

func (UnimplementedApplicationServiceServer) Apply(context.Context, *ApplyRequest) (*ApplicationMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedApplicationServiceServer) GetMyApplications(context.Context, *GetMyApplicationsRequest) (*ApplicationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyApplications not implemented")
}
func (UnimplementedApplicationServiceServer) GetVacancyApplications(context.Context, *GetVacancyApplicationsRequest) (*ApplicationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVacancyApplications not implemented")
}
func (UnimplementedApplicationServiceServer) UpdateStatus(context.Context, *UpdateStatusRequest) (*ApplicationMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedApplicationServiceServer) Withdraw(context.Context, *WithdrawRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Withdraw not implemented")
}
func (UnimplementedApplicationServiceServer) GetApplicationStats(context.Context, *AppStatsEmpty) (*ApplicationStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApplicationStats not implemented")
}
func (UnimplementedApplicationServiceServer) mustEmbedUnimplementedApplicationServiceServer() {}
func (UnimplementedApplicationServiceServer) testEmbeddedByValue()                            {}

// UnsafeApplicationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApplicationServiceServer will
// result in compilation errors.
type UnsafeApplicationServiceServer interface {
	mustEmbedUnimplementedApplicationServiceServer()
}

func RegisterApplicationServiceServer(s grpc.ServiceRegistrar, srv ApplicationServiceServer) {
	// If the following call pancis, it indicates UnimplementedApplicationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApplicationService_ServiceDesc, srv)
}

func _ApplicationService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_GetMyApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).GetMyApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_GetMyApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).GetMyApplications(ctx, req.(*GetMyApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_GetVacancyApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVacancyApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).GetVacancyApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_GetVacancyApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).GetVacancyApplications(ctx, req.(*GetVacancyApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_UpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).UpdateStatus(ctx, req.(*UpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_Withdraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).Withdraw(ctx, req.(*WithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_GetApplicationStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppStatsEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).GetApplicationStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_GetApplicationStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).GetApplicationStats(ctx, req.(*AppStatsEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

// ApplicationService_ServiceDesc is the grpc.ServiceDesc for ApplicationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApplicationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "application.ApplicationService",
	HandlerType: (*ApplicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _ApplicationService_Apply_Handler,
		},
		{
			MethodName: "GetMyApplications",
			Handler:    _ApplicationService_GetMyApplications_Handler,
		},
		{
			MethodName: "GetVacancyApplications",
			Handler:    _ApplicationService_GetVacancyApplications_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _ApplicationService_UpdateStatus_Handler,
		},
		{
			MethodName: "Withdraw",
			Handler:    _ApplicationService_Withdraw_Handler,
		},
		{
			MethodName: "GetApplicationStats",
			Handler:    _ApplicationService_GetApplicationStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "application.proto",
}
