// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: vacancy.proto

package vacancypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllVacanciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	JobType       string                 `protobuf:"bytes,2,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllVacanciesRequest) Reset() {
	*x = GetAllVacanciesRequest{}
	mi := &file_vacancy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllVacanciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllVacanciesRequest) ProtoMessage() {}

func (x *GetAllVacanciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllVacanciesRequest.ProtoReflect.Descriptor instead.
func (*GetAllVacanciesRequest) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllVacanciesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetAllVacanciesRequest) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *GetAllVacanciesRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GetAllVacanciesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllVacanciesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type VacancyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EmployerId    string                 `protobuf:"bytes,2,opt,name=employer_id,json=employerId,proto3" json:"employer_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	SalaryMin     float64                `protobuf:"fixed64,6,opt,name=salary_min,json=salaryMin,proto3" json:"salary_min,omitempty"`
	SalaryMax     float64                `protobuf:"fixed64,7,opt,name=salary_max,json=salaryMax,proto3" json:"salary_max,omitempty"`
	JobType       string                 `protobuf:"bytes,8,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	Skills        string                 `protobuf:"bytes,9,opt,name=skills,proto3" json:"skills,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CompanyName   string                 `protobuf:"bytes,13,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VacancyMessage) Reset() {
	*x = VacancyMessage{}
	mi := &file_vacancy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VacancyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VacancyMessage) ProtoMessage() {}

func (x *VacancyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VacancyMessage.ProtoReflect.Descriptor instead.
func (*VacancyMessage) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{1}
}

func (x *VacancyMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VacancyMessage) GetEmployerId() string {
	if x != nil {
		return x.EmployerId
	}
	return ""
}

func (x *VacancyMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VacancyMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VacancyMessage) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *VacancyMessage) GetSalaryMin() float64 {
	if x != nil {
		return x.SalaryMin
	}
	return 0
}

func (x *VacancyMessage) GetSalaryMax() float64 {
	if x != nil {
		return x.SalaryMax
	}
	return 0
}

func (x *VacancyMessage) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *VacancyMessage) GetSkills() string {
	if x != nil {
		return x.Skills
	}
	return ""
}

func (x *VacancyMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VacancyMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *VacancyMessage) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *VacancyMessage) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

type CreateVacancyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployerId    string                 `protobuf:"bytes,1,opt,name=employer_id,json=employerId,proto3" json:"employer_id,omitempty"`
	EmployerRole  string                 `protobuf:"bytes,2,opt,name=employer_role,json=employerRole,proto3" json:"employer_role,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	SalaryMin     float64                `protobuf:"fixed64,6,opt,name=salary_min,json=salaryMin,proto3" json:"salary_min,omitempty"`
	SalaryMax     float64                `protobuf:"fixed64,7,opt,name=salary_max,json=salaryMax,proto3" json:"salary_max,omitempty"`
	JobType       string                 `protobuf:"bytes,8,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	Skills        string                 `protobuf:"bytes,9,opt,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVacancyRequest) Reset() {
	*x = CreateVacancyRequest{}
	mi := &file_vacancy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVacancyRequest) ProtoMessage() {}

func (x *CreateVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVacancyRequest.ProtoReflect.Descriptor instead.
func (*CreateVacancyRequest) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{2}
}

func (x *CreateVacancyRequest) GetEmployerId() string {
	if x != nil {
		return x.EmployerId
	}
	return ""
}

func (x *CreateVacancyRequest) GetEmployerRole() string {
	if x != nil {
		return x.EmployerRole
	}
	return ""
}

func (x *CreateVacancyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateVacancyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateVacancyRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateVacancyRequest) GetSalaryMin() float64 {
	if x != nil {
		return x.SalaryMin
	}
	return 0
}

func (x *CreateVacancyRequest) GetSalaryMax() float64 {
	if x != nil {
		return x.SalaryMax
	}
	return 0
}

func (x *CreateVacancyRequest) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *CreateVacancyRequest) GetSkills() string {
	if x != nil {
		return x.Skills
	}
	return ""
}

type GetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDRequest) Reset() {
	*x = GetByIDRequest{}
	mi := &file_vacancy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDRequest) ProtoMessage() {}

func (x *GetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{3}
}

func (x *GetByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMyVacanciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployerId    string                 `protobuf:"bytes,1,opt,name=employer_id,json=employerId,proto3" json:"employer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyVacanciesRequest) Reset() {
	*x = GetMyVacanciesRequest{}
	mi := &file_vacancy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyVacanciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyVacanciesRequest) ProtoMessage() {}

func (x *GetMyVacanciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyVacanciesRequest.ProtoReflect.Descriptor instead.
func (*GetMyVacanciesRequest) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{4}
}

func (x *GetMyVacanciesRequest) GetEmployerId() string {
	if x != nil {
		return x.EmployerId
	}
	return ""
}

type UpdateVacancyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EmployerId    string                 `protobuf:"bytes,2,opt,name=employer_id,json=employerId,proto3" json:"employer_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	SalaryMin     float64                `protobuf:"fixed64,6,opt,name=salary_min,json=salaryMin,proto3" json:"salary_min,omitempty"`
	SalaryMax     float64                `protobuf:"fixed64,7,opt,name=salary_max,json=salaryMax,proto3" json:"salary_max,omitempty"`
	JobType       string                 `protobuf:"bytes,8,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	Skills        string                 `protobuf:"bytes,9,opt,name=skills,proto3" json:"skills,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVacancyRequest) Reset() {
	*x = UpdateVacancyRequest{}
	mi := &file_vacancy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVacancyRequest) ProtoMessage() {}

func (x *UpdateVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVacancyRequest.ProtoReflect.Descriptor instead.
func (*UpdateVacancyRequest) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateVacancyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateVacancyRequest) GetEmployerId() string {
	if x != nil {
		return x.EmployerId
	}
	return ""
}

func (x *UpdateVacancyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateVacancyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateVacancyRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateVacancyRequest) GetSalaryMin() float64 {
	if x != nil {
		return x.SalaryMin
	}
	return 0
}

func (x *UpdateVacancyRequest) GetSalaryMax() float64 {
	if x != nil {
		return x.SalaryMax
	}
	return 0
}

func (x *UpdateVacancyRequest) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *UpdateVacancyRequest) GetSkills() string {
	if x != nil {
		return x.Skills
	}
	return ""
}

func (x *UpdateVacancyRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteVacancyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EmployerId    string                 `protobuf:"bytes,2,opt,name=employer_id,json=employerId,proto3" json:"employer_id,omitempty"`
	EmployerRole  string                 `protobuf:"bytes,3,opt,name=employer_role,json=employerRole,proto3" json:"employer_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVacancyRequest) Reset() {
	*x = DeleteVacancyRequest{}
	mi := &file_vacancy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVacancyRequest) ProtoMessage() {}

func (x *DeleteVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVacancyRequest.ProtoReflect.Descriptor instead.
func (*DeleteVacancyRequest) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteVacancyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteVacancyRequest) GetEmployerId() string {
	if x != nil {
		return x.EmployerId
	}
	return ""
}

func (x *DeleteVacancyRequest) GetEmployerRole() string {
	if x != nil {
		return x.EmployerRole
	}
	return ""
}

type VacanciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vacancies     []*VacancyMessage      `protobuf:"bytes,1,rep,name=vacancies,proto3" json:"vacancies,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VacanciesResponse) Reset() {
	*x = VacanciesResponse{}
	mi := &file_vacancy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VacanciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VacanciesResponse) ProtoMessage() {}

func (x *VacanciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VacanciesResponse.ProtoReflect.Descriptor instead.
func (*VacanciesResponse) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{7}
}

func (x *VacanciesResponse) GetVacancies() []*VacancyMessage {
	if x != nil {
		return x.Vacancies
	}
	return nil
}

func (x *VacanciesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_vacancy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EmployerProfileMessage struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EmployerId         string                 `protobuf:"bytes,1,opt,name=employer_id,json=employerId,proto3" json:"employer_id,omitempty"`
	CompanyName        string                 `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	CompanyDescription string                 `protobuf:"bytes,3,opt,name=company_description,json=companyDescription,proto3" json:"company_description,omitempty"`
	Industry           string                 `protobuf:"bytes,4,opt,name=industry,proto3" json:"industry,omitempty"`
	CompanySize        string                 `protobuf:"bytes,5,opt,name=company_size,json=companySize,proto3" json:"company_size,omitempty"`
	Website            string                 `protobuf:"bytes,6,opt,name=website,proto3" json:"website,omitempty"`
	Location           string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	ContactEmail       string                 `protobuf:"bytes,8,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	ContactPhone       string                 `protobuf:"bytes,9,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EmployerProfileMessage) Reset() {
	*x = EmployerProfileMessage{}
	mi := &file_vacancy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployerProfileMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployerProfileMessage) ProtoMessage() {}

func (x *EmployerProfileMessage) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployerProfileMessage.ProtoReflect.Descriptor instead.
func (*EmployerProfileMessage) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{9}
}

func (x *EmployerProfileMessage) GetEmployerId() string {
	if x != nil {
		return x.EmployerId
	}
	return ""
}

func (x *EmployerProfileMessage) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *EmployerProfileMessage) GetCompanyDescription() string {
	if x != nil {
		return x.CompanyDescription
	}
	return ""
}

func (x *EmployerProfileMessage) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *EmployerProfileMessage) GetCompanySize() string {
	if x != nil {
		return x.CompanySize
	}
	return ""
}

func (x *EmployerProfileMessage) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *EmployerProfileMessage) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *EmployerProfileMessage) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *EmployerProfileMessage) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *EmployerProfileMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *EmployerProfileMessage) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetEmployerProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployerId    string                 `protobuf:"bytes,1,opt,name=employer_id,json=employerId,proto3" json:"employer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployerProfileRequest) Reset() {
	*x = GetEmployerProfileRequest{}
	mi := &file_vacancy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployerProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployerProfileRequest) ProtoMessage() {}

func (x *GetEmployerProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployerProfileRequest.ProtoReflect.Descriptor instead.
func (*GetEmployerProfileRequest) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{10}
}

func (x *GetEmployerProfileRequest) GetEmployerId() string {
	if x != nil {
		return x.EmployerId
	}
	return ""
}

type CreateEmployerProfileRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EmployerId         string                 `protobuf:"bytes,1,opt,name=employer_id,json=employerId,proto3" json:"employer_id,omitempty"`
	CompanyName        string                 `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	CompanyDescription string                 `protobuf:"bytes,3,opt,name=company_description,json=companyDescription,proto3" json:"company_description,omitempty"`
	Industry           string                 `protobuf:"bytes,4,opt,name=industry,proto3" json:"industry,omitempty"`
	CompanySize        string                 `protobuf:"bytes,5,opt,name=company_size,json=companySize,proto3" json:"company_size,omitempty"`
	Website            string                 `protobuf:"bytes,6,opt,name=website,proto3" json:"website,omitempty"`
	Location           string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	ContactEmail       string                 `protobuf:"bytes,8,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	ContactPhone       string                 `protobuf:"bytes,9,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateEmployerProfileRequest) Reset() {
	*x = CreateEmployerProfileRequest{}
	mi := &file_vacancy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmployerProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmployerProfileRequest) ProtoMessage() {}

func (x *CreateEmployerProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmployerProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateEmployerProfileRequest) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{11}
}

func (x *CreateEmployerProfileRequest) GetEmployerId() string {
	if x != nil {
		return x.EmployerId
	}
	return ""
}

func (x *CreateEmployerProfileRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *CreateEmployerProfileRequest) GetCompanyDescription() string {
	if x != nil {
		return x.CompanyDescription
	}
	return ""
}

func (x *CreateEmployerProfileRequest) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *CreateEmployerProfileRequest) GetCompanySize() string {
	if x != nil {
		return x.CompanySize
	}
	return ""
}

func (x *CreateEmployerProfileRequest) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *CreateEmployerProfileRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateEmployerProfileRequest) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *CreateEmployerProfileRequest) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

type UpdateEmployerProfileRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EmployerId         string                 `protobuf:"bytes,1,opt,name=employer_id,json=employerId,proto3" json:"employer_id,omitempty"`
	CompanyName        string                 `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	CompanyDescription string                 `protobuf:"bytes,3,opt,name=company_description,json=companyDescription,proto3" json:"company_description,omitempty"`
	Industry           string                 `protobuf:"bytes,4,opt,name=industry,proto3" json:"industry,omitempty"`
	CompanySize        string                 `protobuf:"bytes,5,opt,name=company_size,json=companySize,proto3" json:"company_size,omitempty"`
	Website            string                 `protobuf:"bytes,6,opt,name=website,proto3" json:"website,omitempty"`
	Location           string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	ContactEmail       string                 `protobuf:"bytes,8,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	ContactPhone       string                 `protobuf:"bytes,9,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateEmployerProfileRequest) Reset() {
	*x = UpdateEmployerProfileRequest{}
	mi := &file_vacancy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmployerProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmployerProfileRequest) ProtoMessage() {}

func (x *UpdateEmployerProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vacancy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmployerProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmployerProfileRequest) Descriptor() ([]byte, []int) {
	return file_vacancy_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateEmployerProfileRequest) GetEmployerId() string {
	if x != nil {
		return x.EmployerId
	}
	return ""
}

func (x *UpdateEmployerProfileRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *UpdateEmployerProfileRequest) GetCompanyDescription() string {
	if x != nil {
		return x.CompanyDescription
	}
	return ""
}

func (x *UpdateEmployerProfileRequest) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *UpdateEmployerProfileRequest) GetCompanySize() string {
	if x != nil {
		return x.CompanySize
	}
	return ""
}

func (x *UpdateEmployerProfileRequest) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *UpdateEmployerProfileRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateEmployerProfileRequest) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *UpdateEmployerProfileRequest) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

var File_vacancy_proto protoreflect.FileDescriptor

const file_vacancy_proto_rawDesc = "" +
	"\n" +
	"\rvacancy.proto\x12\avacancy\"\x98\x01\n" +
	"\x16GetAllVacanciesRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\x12\x19\n" +
	"\bjob_type\x18\x02 \x01(\tR\ajobType\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"\xff\x02\n" +
	"\x0eVacancyMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vemployer_id\x18\x02 \x01(\tR\n" +
	"employerId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"salary_min\x18\x06 \x01(\x01R\tsalaryMin\x12\x1d\n" +
	"\n" +
	"salary_max\x18\a \x01(\x01R\tsalaryMax\x12\x19\n" +
	"\bjob_type\x18\b \x01(\tR\ajobType\x12\x16\n" +
	"\x06skills\x18\t \x01(\tR\x06skills\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\x12!\n" +
	"\fcompany_name\x18\r \x01(\tR\vcompanyName\"\xa1\x02\n" +
	"\x14CreateVacancyRequest\x12\x1f\n" +
	"\vemployer_id\x18\x01 \x01(\tR\n" +
	"employerId\x12#\n" +
	"\remployer_role\x18\x02 \x01(\tR\femployerRole\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"salary_min\x18\x06 \x01(\x01R\tsalaryMin\x12\x1d\n" +
	"\n" +
	"salary_max\x18\a \x01(\x01R\tsalaryMax\x12\x19\n" +
	"\bjob_type\x18\b \x01(\tR\ajobType\x12\x16\n" +
	"\x06skills\x18\t \x01(\tR\x06skills\" \n" +
	"\x0eGetByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x15GetMyVacanciesRequest\x12\x1f\n" +
	"\vemployer_id\x18\x01 \x01(\tR\n" +
	"employerId\"\xa4\x02\n" +
	"\x14UpdateVacancyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vemployer_id\x18\x02 \x01(\tR\n" +
	"employerId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"salary_min\x18\x06 \x01(\x01R\tsalaryMin\x12\x1d\n" +
	"\n" +
	"salary_max\x18\a \x01(\x01R\tsalaryMax\x12\x19\n" +
	"\bjob_type\x18\b \x01(\tR\ajobType\x12\x16\n" +
	"\x06skills\x18\t \x01(\tR\x06skills\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\"l\n" +
	"\x14DeleteVacancyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vemployer_id\x18\x02 \x01(\tR\n" +
	"employerId\x12#\n" +
	"\remployer_role\x18\x03 \x01(\tR\femployerRole\"`\n" +
	"\x11VacanciesResponse\x125\n" +
	"\tvacancies\x18\x01 \x03(\v2\x17.vacancy.VacancyMessageR\tvacancies\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x8a\x03\n" +
	"\x16EmployerProfileMessage\x12\x1f\n" +
	"\vemployer_id\x18\x01 \x01(\tR\n" +
	"employerId\x12!\n" +
	"\fcompany_name\x18\x02 \x01(\tR\vcompanyName\x12/\n" +
	"\x13company_description\x18\x03 \x01(\tR\x12companyDescription\x12\x1a\n" +
	"\bindustry\x18\x04 \x01(\tR\bindustry\x12!\n" +
	"\fcompany_size\x18\x05 \x01(\tR\vcompanySize\x12\x18\n" +
	"\awebsite\x18\x06 \x01(\tR\awebsite\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12#\n" +
	"\rcontact_email\x18\b \x01(\tR\fcontactEmail\x12#\n" +
	"\rcontact_phone\x18\t \x01(\tR\fcontactPhone\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\"<\n" +
	"\x19GetEmployerProfileRequest\x12\x1f\n" +
	"\vemployer_id\x18\x01 \x01(\tR\n" +
	"employerId\"\xd2\x02\n" +
	"\x1cCreateEmployerProfileRequest\x12\x1f\n" +
	"\vemployer_id\x18\x01 \x01(\tR\n" +
	"employerId\x12!\n" +
	"\fcompany_name\x18\x02 \x01(\tR\vcompanyName\x12/\n" +
	"\x13company_description\x18\x03 \x01(\tR\x12companyDescription\x12\x1a\n" +
	"\bindustry\x18\x04 \x01(\tR\bindustry\x12!\n" +
	"\fcompany_size\x18\x05 \x01(\tR\vcompanySize\x12\x18\n" +
	"\awebsite\x18\x06 \x01(\tR\awebsite\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12#\n" +
	"\rcontact_email\x18\b \x01(\tR\fcontactEmail\x12#\n" +
	"\rcontact_phone\x18\t \x01(\tR\fcontactPhone\"\xd2\x02\n" +
	"\x1cUpdateEmployerProfileRequest\x12\x1f\n" +
	"\vemployer_id\x18\x01 \x01(\tR\n" +
	"employerId\x12!\n" +
	"\fcompany_name\x18\x02 \x01(\tR\vcompanyName\x12/\n" +
	"\x13company_description\x18\x03 \x01(\tR\x12companyDescription\x12\x1a\n" +
	"\bindustry\x18\x04 \x01(\tR\bindustry\x12!\n" +
	"\fcompany_size\x18\x05 \x01(\tR\vcompanySize\x12\x18\n" +
	"\awebsite\x18\x06 \x01(\tR\awebsite\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12#\n" +
	"\rcontact_email\x18\b \x01(\tR\fcontactEmail\x12#\n" +
	"\rcontact_phone\x18\t \x01(\tR\fcontactPhone2\xea\x05\n" +
	"\x0eVacancyService\x12G\n" +
	"\rCreateVacancy\x12\x1d.vacancy.CreateVacancyRequest\x1a\x17.vacancy.VacancyMessage\x12N\n" +
	"\x0fGetAllVacancies\x12\x1f.vacancy.GetAllVacanciesRequest\x1a\x1a.vacancy.VacanciesResponse\x12B\n" +
	"\x0eGetVacancyByID\x12\x17.vacancy.GetByIDRequest\x1a\x17.vacancy.VacancyMessage\x12L\n" +
	"\x0eGetMyVacancies\x12\x1e.vacancy.GetMyVacanciesRequest\x1a\x1a.vacancy.VacanciesResponse\x12G\n" +
	"\rUpdateVacancy\x12\x1d.vacancy.UpdateVacancyRequest\x1a\x17.vacancy.VacancyMessage\x12G\n" +
	"\rDeleteVacancy\x12\x1d.vacancy.DeleteVacancyRequest\x1a\x17.vacancy.DeleteResponse\x12Y\n" +
	"\x12GetEmployerProfile\x12\".vacancy.GetEmployerProfileRequest\x1a\x1f.vacancy.EmployerProfileMessage\x12_\n" +
	"\x15CreateEmployerProfile\x12%.vacancy.CreateEmployerProfileRequest\x1a\x1f.vacancy.EmployerProfileMessage\x12_\n" +
	"\x15UpdateEmployerProfile\x12%.vacancy.UpdateEmployerProfileRequest\x1a\x1f.vacancy.EmployerProfileMessageB&Z$employer-service/internal/grpc/pb;pbb\x06proto3"

var (
	file_vacancy_proto_rawDescOnce sync.Once
	file_vacancy_proto_rawDescData []byte
)

func file_vacancy_proto_rawDescGZIP() []byte {
	file_vacancy_proto_rawDescOnce.Do(func() {
		file_vacancy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vacancy_proto_rawDesc), len(file_vacancy_proto_rawDesc)))
	})
	return file_vacancy_proto_rawDescData
}

var file_vacancy_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_vacancy_proto_goTypes = []any{
	(*GetAllVacanciesRequest)(nil),       // 0: vacancy.GetAllVacanciesRequest
	(*VacancyMessage)(nil),               // 1: vacancy.VacancyMessage
	(*CreateVacancyRequest)(nil),         // 2: vacancy.CreateVacancyRequest
	(*GetByIDRequest)(nil),               // 3: vacancy.GetByIDRequest
	(*GetMyVacanciesRequest)(nil),        // 4: vacancy.GetMyVacanciesRequest
	(*UpdateVacancyRequest)(nil),         // 5: vacancy.UpdateVacancyRequest
	(*DeleteVacancyRequest)(nil),         // 6: vacancy.DeleteVacancyRequest
	(*VacanciesResponse)(nil),            // 7: vacancy.VacanciesResponse
	(*DeleteResponse)(nil),               // 8: vacancy.DeleteResponse
	(*EmployerProfileMessage)(nil),       // 9: vacancy.EmployerProfileMessage
	(*GetEmployerProfileRequest)(nil),    // 10: vacancy.GetEmployerProfileRequest
	(*CreateEmployerProfileRequest)(nil), // 11: vacancy.CreateEmployerProfileRequest
	(*UpdateEmployerProfileRequest)(nil), // 12: vacancy.UpdateEmployerProfileRequest
}
var file_vacancy_proto_depIdxs = []int32{
	1,  // 0: vacancy.VacanciesResponse.vacancies:type_name -> vacancy.VacancyMessage
	2,  // 1: vacancy.VacancyService.CreateVacancy:input_type -> vacancy.CreateVacancyRequest
	0,  // 2: vacancy.VacancyService.GetAllVacancies:input_type -> vacancy.GetAllVacanciesRequest
	3,  // 3: vacancy.VacancyService.GetVacancyByID:input_type -> vacancy.GetByIDRequest
	4,  // 4: vacancy.VacancyService.GetMyVacancies:input_type -> vacancy.GetMyVacanciesRequest
	5,  // 5: vacancy.VacancyService.UpdateVacancy:input_type -> vacancy.UpdateVacancyRequest
	6,  // 6: vacancy.VacancyService.DeleteVacancy:input_type -> vacancy.DeleteVacancyRequest
	10, // 7: vacancy.VacancyService.GetEmployerProfile:input_type -> vacancy.GetEmployerProfileRequest
	11, // 8: vacancy.VacancyService.CreateEmployerProfile:input_type -> vacancy.CreateEmployerProfileRequest
	12, // 9: vacancy.VacancyService.UpdateEmployerProfile:input_type -> vacancy.UpdateEmployerProfileRequest
	1,  // 10: vacancy.VacancyService.CreateVacancy:output_type -> vacancy.VacancyMessage
	7,  // 11: vacancy.VacancyService.GetAllVacancies:output_type -> vacancy.VacanciesResponse
	1,  // 12: vacancy.VacancyService.GetVacancyByID:output_type -> vacancy.VacancyMessage
	7,  // 13: vacancy.VacancyService.GetMyVacancies:output_type -> vacancy.VacanciesResponse
	1,  // 14: vacancy.VacancyService.UpdateVacancy:output_type -> vacancy.VacancyMessage
	8,  // 15: vacancy.VacancyService.DeleteVacancy:output_type -> vacancy.DeleteResponse
	9,  // 16: vacancy.VacancyService.GetEmployerProfile:output_type -> vacancy.EmployerProfileMessage
	9,  // 17: vacancy.VacancyService.CreateEmployerProfile:output_type -> vacancy.EmployerProfileMessage
	9,  // 18: vacancy.VacancyService.UpdateEmployerProfile:output_type -> vacancy.EmployerProfileMessage
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_vacancy_proto_init() }
func file_vacancy_proto_init() {
	if File_vacancy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vacancy_proto_rawDesc), len(file_vacancy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vacancy_proto_goTypes,
		DependencyIndexes: file_vacancy_proto_depIdxs,
		MessageInfos:      file_vacancy_proto_msgTypes,
	}.Build()
	File_vacancy_proto = out.File
	file_vacancy_proto_goTypes = nil
	file_vacancy_proto_depIdxs = nil
}
