// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: university.proto

package universitypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UniversityService_CreateUniversity_FullMethodName   = "/university.UniversityService/CreateUniversity"
	UniversityService_GetAllUniversities_FullMethodName = "/university.UniversityService/GetAllUniversities"
	UniversityService_GetUniversityByID_FullMethodName  = "/university.UniversityService/GetUniversityByID"
	UniversityService_UpdateUniversity_FullMethodName   = "/university.UniversityService/UpdateUniversity"
	UniversityService_DeleteUniversity_FullMethodName   = "/university.UniversityService/DeleteUniversity"
)

// UniversityServiceClient is the client API for UniversityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UniversityServiceClient interface {
	CreateUniversity(ctx context.Context, in *CreateUniversityRequest, opts ...grpc.CallOption) (*UniversityMessage, error)
	GetAllUniversities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UniversitiesResponse, error)
	GetUniversityByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*UniversityMessage, error)
	UpdateUniversity(ctx context.Context, in *UpdateUniversityRequest, opts ...grpc.CallOption) (*UniversityMessage, error)
	DeleteUniversity(ctx context.Context, in *DeleteUniversityRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type universityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUniversityServiceClient(cc grpc.ClientConnInterface) UniversityServiceClient {
	return &universityServiceClient{cc}
}

func (c *universityServiceClient) CreateUniversity(ctx context.Context, in *CreateUniversityRequest, opts ...grpc.CallOption) (*UniversityMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UniversityMessage)
	err := c.cc.Invoke(ctx, UniversityService_CreateUniversity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityServiceClient) GetAllUniversities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UniversitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UniversitiesResponse)
	err := c.cc.Invoke(ctx, UniversityService_GetAllUniversities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityServiceClient) GetUniversityByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*UniversityMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UniversityMessage)
	err := c.cc.Invoke(ctx, UniversityService_GetUniversityByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityServiceClient) UpdateUniversity(ctx context.Context, in *UpdateUniversityRequest, opts ...grpc.CallOption) (*UniversityMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UniversityMessage)
	err := c.cc.Invoke(ctx, UniversityService_UpdateUniversity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityServiceClient) DeleteUniversity(ctx context.Context, in *DeleteUniversityRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, UniversityService_DeleteUniversity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UniversityServiceServer is the server API for UniversityService service.
// All implementations must embed UnimplementedUniversityServiceServer
// for forward compatibility.
type UniversityServiceServer interface {
	CreateUniversity(context.Context, *CreateUniversityRequest) (*UniversityMessage, error)
	GetAllUniversities(context.Context, *Empty) (*UniversitiesResponse, error)
	GetUniversityByID(context.Context, *GetByIDRequest) (*UniversityMessage, error)
	UpdateUniversity(context.Context, *UpdateUniversityRequest) (*UniversityMessage, error)
	DeleteUniversity(context.Context, *DeleteUniversityRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedUniversityServiceServer()
}

// UnimplementedUniversityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUniversityServiceServer struct{}

func (UnimplementedUniversityServiceServer) CreateUniversity(context.Context, *CreateUniversityRequest) (*UniversityMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUniversity not implemented")
}
func (UnimplementedUniversityServiceServer) GetAllUniversities(context.Context, *Empty) (*UniversitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllUniversities not implemented")
}
func (UnimplementedUniversityServiceServer) GetUniversityByID(context.Context, *GetByIDRequest) (*UniversityMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUniversityByID not implemented")
}
func (UnimplementedUniversityServiceServer) UpdateUniversity(context.Context, *UpdateUniversityRequest) (*UniversityMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUniversity not implemented")
}
func (UnimplementedUniversityServiceServer) DeleteUniversity(context.Context, *DeleteUniversityRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUniversity not implemented")
}
func (UnimplementedUniversityServiceServer) mustEmbedUnimplementedUniversityServiceServer() {}
func (UnimplementedUniversityServiceServer) testEmbeddedByValue()                           {}

// UnsafeUniversityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UniversityServiceServer will
// result in compilation errors.
type UnsafeUniversityServiceServer interface {
	mustEmbedUnimplementedUniversityServiceServer()
}

func RegisterUniversityServiceServer(s grpc.ServiceRegistrar, srv UniversityServiceServer) {
	// If the following call pancis, it indicates UnimplementedUniversityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UniversityService_ServiceDesc, srv)
}

func _UniversityService_CreateUniversity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUniversityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityServiceServer).CreateUniversity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UniversityService_CreateUniversity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityServiceServer).CreateUniversity(ctx, req.(*CreateUniversityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityService_GetAllUniversities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityServiceServer).GetAllUniversities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UniversityService_GetAllUniversities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityServiceServer).GetAllUniversities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityService_GetUniversityByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityServiceServer).GetUniversityByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UniversityService_GetUniversityByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityServiceServer).GetUniversityByID(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityService_UpdateUniversity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUniversityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityServiceServer).UpdateUniversity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UniversityService_UpdateUniversity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityServiceServer).UpdateUniversity(ctx, req.(*UpdateUniversityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityService_DeleteUniversity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUniversityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityServiceServer).DeleteUniversity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UniversityService_DeleteUniversity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityServiceServer).DeleteUniversity(ctx, req.(*DeleteUniversityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UniversityService_ServiceDesc is the grpc.ServiceDesc for UniversityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UniversityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "university.UniversityService",
	HandlerType: (*UniversityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUniversity",
			Handler:    _UniversityService_CreateUniversity_Handler,
		},
		{
			MethodName: "GetAllUniversities",
			Handler:    _UniversityService_GetAllUniversities_Handler,
		},
		{
			MethodName: "GetUniversityByID",
			Handler:    _UniversityService_GetUniversityByID_Handler,
		},
		{
			MethodName: "UpdateUniversity",
			Handler:    _UniversityService_UpdateUniversity_Handler,
		},
		{
			MethodName: "DeleteUniversity",
			Handler:    _UniversityService_DeleteUniversity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "university.proto",
}
