// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: vacancy.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VacancyService_CreateVacancy_FullMethodName         = "/vacancy.VacancyService/CreateVacancy"
	VacancyService_GetAllVacancies_FullMethodName       = "/vacancy.VacancyService/GetAllVacancies"
	VacancyService_GetVacancyByID_FullMethodName        = "/vacancy.VacancyService/GetVacancyByID"
	VacancyService_GetMyVacancies_FullMethodName        = "/vacancy.VacancyService/GetMyVacancies"
	VacancyService_UpdateVacancy_FullMethodName         = "/vacancy.VacancyService/UpdateVacancy"
	VacancyService_DeleteVacancy_FullMethodName         = "/vacancy.VacancyService/DeleteVacancy"
	VacancyService_GetEmployerProfile_FullMethodName    = "/vacancy.VacancyService/GetEmployerProfile"
	VacancyService_CreateEmployerProfile_FullMethodName = "/vacancy.VacancyService/CreateEmployerProfile"
	VacancyService_UpdateEmployerProfile_FullMethodName = "/vacancy.VacancyService/UpdateEmployerProfile"
)

// VacancyServiceClient is the client API for VacancyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VacancyServiceClient interface {
	CreateVacancy(ctx context.Context, in *CreateVacancyRequest, opts ...grpc.CallOption) (*VacancyMessage, error)
	GetAllVacancies(ctx context.Context, in *GetAllVacanciesRequest, opts ...grpc.CallOption) (*VacanciesResponse, error)
	GetVacancyByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*VacancyMessage, error)
	GetMyVacancies(ctx context.Context, in *GetMyVacanciesRequest, opts ...grpc.CallOption) (*VacanciesResponse, error)
	UpdateVacancy(ctx context.Context, in *UpdateVacancyRequest, opts ...grpc.CallOption) (*VacancyMessage, error)
	DeleteVacancy(ctx context.Context, in *DeleteVacancyRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Employer profile
	GetEmployerProfile(ctx context.Context, in *GetEmployerProfileRequest, opts ...grpc.CallOption) (*EmployerProfileMessage, error)
	CreateEmployerProfile(ctx context.Context, in *CreateEmployerProfileRequest, opts ...grpc.CallOption) (*EmployerProfileMessage, error)
	UpdateEmployerProfile(ctx context.Context, in *UpdateEmployerProfileRequest, opts ...grpc.CallOption) (*EmployerProfileMessage, error)
}

type vacancyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVacancyServiceClient(cc grpc.ClientConnInterface) VacancyServiceClient {
	return &vacancyServiceClient{cc}
}

func (c *vacancyServiceClient) CreateVacancy(ctx context.Context, in *CreateVacancyRequest, opts ...grpc.CallOption) (*VacancyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VacancyMessage)
	err := c.cc.Invoke(ctx, VacancyService_CreateVacancy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vacancyServiceClient) GetAllVacancies(ctx context.Context, in *GetAllVacanciesRequest, opts ...grpc.CallOption) (*VacanciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VacanciesResponse)
	err := c.cc.Invoke(ctx, VacancyService_GetAllVacancies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vacancyServiceClient) GetVacancyByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*VacancyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VacancyMessage)
	err := c.cc.Invoke(ctx, VacancyService_GetVacancyByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vacancyServiceClient) GetMyVacancies(ctx context.Context, in *GetMyVacanciesRequest, opts ...grpc.CallOption) (*VacanciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VacanciesResponse)
	err := c.cc.Invoke(ctx, VacancyService_GetMyVacancies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vacancyServiceClient) UpdateVacancy(ctx context.Context, in *UpdateVacancyRequest, opts ...grpc.CallOption) (*VacancyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VacancyMessage)
	err := c.cc.Invoke(ctx, VacancyService_UpdateVacancy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vacancyServiceClient) DeleteVacancy(ctx context.Context, in *DeleteVacancyRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, VacancyService_DeleteVacancy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vacancyServiceClient) GetEmployerProfile(ctx context.Context, in *GetEmployerProfileRequest, opts ...grpc.CallOption) (*EmployerProfileMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmployerProfileMessage)
	err := c.cc.Invoke(ctx, VacancyService_GetEmployerProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vacancyServiceClient) CreateEmployerProfile(ctx context.Context, in *CreateEmployerProfileRequest, opts ...grpc.CallOption) (*EmployerProfileMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmployerProfileMessage)
	err := c.cc.Invoke(ctx, VacancyService_CreateEmployerProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vacancyServiceClient) UpdateEmployerProfile(ctx context.Context, in *UpdateEmployerProfileRequest, opts ...grpc.CallOption) (*EmployerProfileMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmployerProfileMessage)
	err := c.cc.Invoke(ctx, VacancyService_UpdateEmployerProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VacancyServiceServer is the server API for VacancyService service.
// All implementations must embed UnimplementedVacancyServiceServer
// for forward compatibility.
type VacancyServiceServer interface {
	CreateVacancy(context.Context, *CreateVacancyRequest) (*VacancyMessage, error)
	GetAllVacancies(context.Context, *GetAllVacanciesRequest) (*VacanciesResponse, error)
	GetVacancyByID(context.Context, *GetByIDRequest) (*VacancyMessage, error)
	GetMyVacancies(context.Context, *GetMyVacanciesRequest) (*VacanciesResponse, error)
	UpdateVacancy(context.Context, *UpdateVacancyRequest) (*VacancyMessage, error)
	DeleteVacancy(context.Context, *DeleteVacancyRequest) (*DeleteResponse, error)
	// Employer profile
	GetEmployerProfile(context.Context, *GetEmployerProfileRequest) (*EmployerProfileMessage, error)
	CreateEmployerProfile(context.Context, *CreateEmployerProfileRequest) (*EmployerProfileMessage, error)
	UpdateEmployerProfile(context.Context, *UpdateEmployerProfileRequest) (*EmployerProfileMessage, error)
	mustEmbedUnimplementedVacancyServiceServer()
}

// UnimplementedVacancyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVacancyServiceServer struct{}

func (UnimplementedVacancyServiceServer) CreateVacancy(context.Context, *CreateVacancyRequest) (*VacancyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVacancy not implemented")
}
func (UnimplementedVacancyServiceServer) GetAllVacancies(context.Context, *GetAllVacanciesRequest) (*VacanciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllVacancies not implemented")
}
func (UnimplementedVacancyServiceServer) GetVacancyByID(context.Context, *GetByIDRequest) (*VacancyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVacancyByID not implemented")
}
func (UnimplementedVacancyServiceServer) GetMyVacancies(context.Context, *GetMyVacanciesRequest) (*VacanciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyVacancies not implemented")
}
func (UnimplementedVacancyServiceServer) UpdateVacancy(context.Context, *UpdateVacancyRequest) (*VacancyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVacancy not implemented")
}
func (UnimplementedVacancyServiceServer) DeleteVacancy(context.Context, *DeleteVacancyRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVacancy not implemented")
}
func (UnimplementedVacancyServiceServer) GetEmployerProfile(context.Context, *GetEmployerProfileRequest) (*EmployerProfileMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployerProfile not implemented")
}
func (UnimplementedVacancyServiceServer) CreateEmployerProfile(context.Context, *CreateEmployerProfileRequest) (*EmployerProfileMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEmployerProfile not implemented")
}
func (UnimplementedVacancyServiceServer) UpdateEmployerProfile(context.Context, *UpdateEmployerProfileRequest) (*EmployerProfileMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEmployerProfile not implemented")
}
func (UnimplementedVacancyServiceServer) mustEmbedUnimplementedVacancyServiceServer() {}
func (UnimplementedVacancyServiceServer) testEmbeddedByValue()                        {}

// UnsafeVacancyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VacancyServiceServer will
// result in compilation errors.
type UnsafeVacancyServiceServer interface {
	mustEmbedUnimplementedVacancyServiceServer()
}

func RegisterVacancyServiceServer(s grpc.ServiceRegistrar, srv VacancyServiceServer) {
	// If the following call pancis, it indicates UnimplementedVacancyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VacancyService_ServiceDesc, srv)
}

func _VacancyService_CreateVacancy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVacancyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServiceServer).CreateVacancy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VacancyService_CreateVacancy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServiceServer).CreateVacancy(ctx, req.(*CreateVacancyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VacancyService_GetAllVacancies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllVacanciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServiceServer).GetAllVacancies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VacancyService_GetAllVacancies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServiceServer).GetAllVacancies(ctx, req.(*GetAllVacanciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VacancyService_GetVacancyByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServiceServer).GetVacancyByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VacancyService_GetVacancyByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServiceServer).GetVacancyByID(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VacancyService_GetMyVacancies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyVacanciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServiceServer).GetMyVacancies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VacancyService_GetMyVacancies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServiceServer).GetMyVacancies(ctx, req.(*GetMyVacanciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VacancyService_UpdateVacancy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVacancyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServiceServer).UpdateVacancy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VacancyService_UpdateVacancy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServiceServer).UpdateVacancy(ctx, req.(*UpdateVacancyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VacancyService_DeleteVacancy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVacancyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServiceServer).DeleteVacancy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VacancyService_DeleteVacancy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServiceServer).DeleteVacancy(ctx, req.(*DeleteVacancyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VacancyService_GetEmployerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployerProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServiceServer).GetEmployerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VacancyService_GetEmployerProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServiceServer).GetEmployerProfile(ctx, req.(*GetEmployerProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VacancyService_CreateEmployerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEmployerProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServiceServer).CreateEmployerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VacancyService_CreateEmployerProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServiceServer).CreateEmployerProfile(ctx, req.(*CreateEmployerProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VacancyService_UpdateEmployerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEmployerProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServiceServer).UpdateEmployerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VacancyService_UpdateEmployerProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServiceServer).UpdateEmployerProfile(ctx, req.(*UpdateEmployerProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VacancyService_ServiceDesc is the grpc.ServiceDesc for VacancyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VacancyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vacancy.VacancyService",
	HandlerType: (*VacancyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVacancy",
			Handler:    _VacancyService_CreateVacancy_Handler,
		},
		{
			MethodName: "GetAllVacancies",
			Handler:    _VacancyService_GetAllVacancies_Handler,
		},
		{
			MethodName: "GetVacancyByID",
			Handler:    _VacancyService_GetVacancyByID_Handler,
		},
		{
			MethodName: "GetMyVacancies",
			Handler:    _VacancyService_GetMyVacancies_Handler,
		},
		{
			MethodName: "UpdateVacancy",
			Handler:    _VacancyService_UpdateVacancy_Handler,
		},
		{
			MethodName: "DeleteVacancy",
			Handler:    _VacancyService_DeleteVacancy_Handler,
		},
		{
			MethodName: "GetEmployerProfile",
			Handler:    _VacancyService_GetEmployerProfile_Handler,
		},
		{
			MethodName: "CreateEmployerProfile",
			Handler:    _VacancyService_CreateEmployerProfile_Handler,
		},
		{
			MethodName: "UpdateEmployerProfile",
			Handler:    _VacancyService_UpdateEmployerProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vacancy.proto",
}
