// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: application.proto

package applicationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppStatsEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppStatsEmpty) Reset() {
	*x = AppStatsEmpty{}
	mi := &file_application_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppStatsEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppStatsEmpty) ProtoMessage() {}

func (x *AppStatsEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppStatsEmpty.ProtoReflect.Descriptor instead.
func (*AppStatsEmpty) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{0}
}

type StatusCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusCount) Reset() {
	*x = StatusCount{}
	mi := &file_application_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusCount) ProtoMessage() {}

func (x *StatusCount) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusCount.ProtoReflect.Descriptor instead.
func (*StatusCount) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{1}
}

func (x *StatusCount) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ApplicationStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	OfferedCount  int32                  `protobuf:"varint,2,opt,name=offered_count,json=offeredCount,proto3" json:"offered_count,omitempty"`
	ByStatus      []*StatusCount         `protobuf:"bytes,3,rep,name=by_status,json=byStatus,proto3" json:"by_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationStatsResponse) Reset() {
	*x = ApplicationStatsResponse{}
	mi := &file_application_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationStatsResponse) ProtoMessage() {}

func (x *ApplicationStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationStatsResponse.ProtoReflect.Descriptor instead.
func (*ApplicationStatsResponse) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{2}
}

func (x *ApplicationStatsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ApplicationStatsResponse) GetOfferedCount() int32 {
	if x != nil {
		return x.OfferedCount
	}
	return 0
}

func (x *ApplicationStatsResponse) GetByStatus() []*StatusCount {
	if x != nil {
		return x.ByStatus
	}
	return nil
}

type ApplicationMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentId        string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	VacancyId        string                 `protobuf:"bytes,3,opt,name=vacancy_id,json=vacancyId,proto3" json:"vacancy_id,omitempty"`
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CoverLetter      string                 `protobuf:"bytes,5,opt,name=cover_letter,json=coverLetter,proto3" json:"cover_letter,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	StudentFirstName string                 `protobuf:"bytes,8,opt,name=student_first_name,json=studentFirstName,proto3" json:"student_first_name,omitempty"`
	StudentLastName  string                 `protobuf:"bytes,9,opt,name=student_last_name,json=studentLastName,proto3" json:"student_last_name,omitempty"`
	StudentIin       string                 `protobuf:"bytes,10,opt,name=student_iin,json=studentIin,proto3" json:"student_iin,omitempty"`
	UniversityId     string                 `protobuf:"bytes,11,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	MatchScore       int32                  `protobuf:"varint,12,opt,name=match_score,json=matchScore,proto3" json:"match_score,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApplicationMessage) Reset() {
	*x = ApplicationMessage{}
	mi := &file_application_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationMessage) ProtoMessage() {}

func (x *ApplicationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationMessage.ProtoReflect.Descriptor instead.
func (*ApplicationMessage) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{3}
}

func (x *ApplicationMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApplicationMessage) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ApplicationMessage) GetVacancyId() string {
	if x != nil {
		return x.VacancyId
	}
	return ""
}

func (x *ApplicationMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApplicationMessage) GetCoverLetter() string {
	if x != nil {
		return x.CoverLetter
	}
	return ""
}

func (x *ApplicationMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ApplicationMessage) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ApplicationMessage) GetStudentFirstName() string {
	if x != nil {
		return x.StudentFirstName
	}
	return ""
}

func (x *ApplicationMessage) GetStudentLastName() string {
	if x != nil {
		return x.StudentLastName
	}
	return ""
}

func (x *ApplicationMessage) GetStudentIin() string {
	if x != nil {
		return x.StudentIin
	}
	return ""
}

func (x *ApplicationMessage) GetUniversityId() string {
	if x != nil {
		return x.UniversityId
	}
	return ""
}

func (x *ApplicationMessage) GetMatchScore() int32 {
	if x != nil {
		return x.MatchScore
	}
	return 0
}

type ApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	VacancyId     string                 `protobuf:"bytes,2,opt,name=vacancy_id,json=vacancyId,proto3" json:"vacancy_id,omitempty"`
	CoverLetter   string                 `protobuf:"bytes,3,opt,name=cover_letter,json=coverLetter,proto3" json:"cover_letter,omitempty"`
	MatchScore    int32                  `protobuf:"varint,4,opt,name=match_score,json=matchScore,proto3" json:"match_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_application_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{4}
}

func (x *ApplyRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ApplyRequest) GetVacancyId() string {
	if x != nil {
		return x.VacancyId
	}
	return ""
}

func (x *ApplyRequest) GetCoverLetter() string {
	if x != nil {
		return x.CoverLetter
	}
	return ""
}

func (x *ApplyRequest) GetMatchScore() int32 {
	if x != nil {
		return x.MatchScore
	}
	return 0
}

type GetMyApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyApplicationsRequest) Reset() {
	*x = GetMyApplicationsRequest{}
	mi := &file_application_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyApplicationsRequest) ProtoMessage() {}

func (x *GetMyApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyApplicationsRequest.ProtoReflect.Descriptor instead.
func (*GetMyApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{5}
}

func (x *GetMyApplicationsRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type GetVacancyApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VacancyId     string                 `protobuf:"bytes,1,opt,name=vacancy_id,json=vacancyId,proto3" json:"vacancy_id,omitempty"`
	EmployerId    string                 `protobuf:"bytes,2,opt,name=employer_id,json=employerId,proto3" json:"employer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVacancyApplicationsRequest) Reset() {
	*x = GetVacancyApplicationsRequest{}
	mi := &file_application_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVacancyApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVacancyApplicationsRequest) ProtoMessage() {}

func (x *GetVacancyApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVacancyApplicationsRequest.ProtoReflect.Descriptor instead.
func (*GetVacancyApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{6}
}

func (x *GetVacancyApplicationsRequest) GetVacancyId() string {
	if x != nil {
		return x.VacancyId
	}
	return ""
}

func (x *GetVacancyApplicationsRequest) GetEmployerId() string {
	if x != nil {
		return x.EmployerId
	}
	return ""
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EmployerId    string                 `protobuf:"bytes,2,opt,name=employer_id,json=employerId,proto3" json:"employer_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_application_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateStatusRequest) GetEmployerId() string {
	if x != nil {
		return x.EmployerId
	}
	return ""
}

func (x *UpdateStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type WithdrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawRequest) Reset() {
	*x = WithdrawRequest{}
	mi := &file_application_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawRequest) ProtoMessage() {}

func (x *WithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawRequest.ProtoReflect.Descriptor instead.
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{8}
}

func (x *WithdrawRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WithdrawRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type ApplicationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applications  []*ApplicationMessage  `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationsResponse) Reset() {
	*x = ApplicationsResponse{}
	mi := &file_application_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationsResponse) ProtoMessage() {}

func (x *ApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationsResponse.ProtoReflect.Descriptor instead.
func (*ApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{9}
}

func (x *ApplicationsResponse) GetApplications() []*ApplicationMessage {
	if x != nil {
		return x.Applications
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_application_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_application_proto protoreflect.FileDescriptor

const file_application_proto_rawDesc = "" +
	"\n" +
	"\x11application.proto\x12\vapplication\"\x0f\n" +
	"\rAppStatsEmpty\";\n" +
	"\vStatusCount\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x8c\x01\n" +
	"\x18ApplicationStatsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12#\n" +
	"\roffered_count\x18\x02 \x01(\x05R\fofferedCount\x125\n" +
	"\tby_status\x18\x03 \x03(\v2\x18.application.StatusCountR\bbyStatus\"\x9c\x03\n" +
	"\x12ApplicationMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x1d\n" +
	"\n" +
	"vacancy_id\x18\x03 \x01(\tR\tvacancyId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12!\n" +
	"\fcover_letter\x18\x05 \x01(\tR\vcoverLetter\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12,\n" +
	"\x12student_first_name\x18\b \x01(\tR\x10studentFirstName\x12*\n" +
	"\x11student_last_name\x18\t \x01(\tR\x0fstudentLastName\x12\x1f\n" +
	"\vstudent_iin\x18\n" +
	" \x01(\tR\n" +
	"studentIin\x12#\n" +
	"\runiversity_id\x18\v \x01(\tR\funiversityId\x12\x1f\n" +
	"\vmatch_score\x18\f \x01(\x05R\n" +
	"matchScore\"\x90\x01\n" +
	"\fApplyRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1d\n" +
	"\n" +
	"vacancy_id\x18\x02 \x01(\tR\tvacancyId\x12!\n" +
	"\fcover_letter\x18\x03 \x01(\tR\vcoverLetter\x12\x1f\n" +
	"\vmatch_score\x18\x04 \x01(\x05R\n" +
	"matchScore\"9\n" +
	"\x18GetMyApplicationsRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"_\n" +
	"\x1dGetVacancyApplicationsRequest\x12\x1d\n" +
	"\n" +
	"vacancy_id\x18\x01 \x01(\tR\tvacancyId\x12\x1f\n" +
	"\vemployer_id\x18\x02 \x01(\tR\n" +
	"employerId\"^\n" +
	"\x13UpdateStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vemployer_id\x18\x02 \x01(\tR\n" +
	"employerId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"@\n" +
	"\x0fWithdrawRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\"[\n" +
	"\x14ApplicationsResponse\x12C\n" +
	"\fapplications\x18\x01 \x03(\v2\x1f.application.ApplicationMessageR\fapplications\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x95\x04\n" +
	"\x12ApplicationService\x12C\n" +
	"\x05Apply\x12\x19.application.ApplyRequest\x1a\x1f.application.ApplicationMessage\x12]\n" +
	"\x11GetMyApplications\x12%.application.GetMyApplicationsRequest\x1a!.application.ApplicationsResponse\x12g\n" +
	"\x16GetVacancyApplications\x12*.application.GetVacancyApplicationsRequest\x1a!.application.ApplicationsResponse\x12Q\n" +
	"\fUpdateStatus\x12 .application.UpdateStatusRequest\x1a\x1f.application.ApplicationMessage\x12E\n" +
	"\bWithdraw\x12\x1c.application.WithdrawRequest\x1a\x1b.application.DeleteResponse\x12X\n" +
	"\x13GetApplicationStats\x12\x1a.application.AppStatsEmpty\x1a%.application.ApplicationStatsResponseB)Z'application-service/internal/grpc/pb;pbb\x06proto3"

var (
	file_application_proto_rawDescOnce sync.Once
	file_application_proto_rawDescData []byte
)

func file_application_proto_rawDescGZIP() []byte {
	file_application_proto_rawDescOnce.Do(func() {
		file_application_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_application_proto_rawDesc), len(file_application_proto_rawDesc)))
	})
	return file_application_proto_rawDescData
}

var file_application_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_application_proto_goTypes = []any{
	(*AppStatsEmpty)(nil),                 // 0: application.AppStatsEmpty
	(*StatusCount)(nil),                   // 1: application.StatusCount
	(*ApplicationStatsResponse)(nil),      // 2: application.ApplicationStatsResponse
	(*ApplicationMessage)(nil),            // 3: application.ApplicationMessage
	(*ApplyRequest)(nil),                  // 4: application.ApplyRequest
	(*GetMyApplicationsRequest)(nil),      // 5: application.GetMyApplicationsRequest
	(*GetVacancyApplicationsRequest)(nil), // 6: application.GetVacancyApplicationsRequest
	(*UpdateStatusRequest)(nil),           // 7: application.UpdateStatusRequest
	(*WithdrawRequest)(nil),               // 8: application.WithdrawRequest
	(*ApplicationsResponse)(nil),          // 9: application.ApplicationsResponse
	(*DeleteResponse)(nil),                // 10: application.DeleteResponse
}
var file_application_proto_depIdxs = []int32{
	1,  // 0: application.ApplicationStatsResponse.by_status:type_name -> application.StatusCount
	3,  // 1: application.ApplicationsResponse.applications:type_name -> application.ApplicationMessage
	4,  // 2: application.ApplicationService.Apply:input_type -> application.ApplyRequest
	5,  // 3: application.ApplicationService.GetMyApplications:input_type -> application.GetMyApplicationsRequest
	6,  // 4: application.ApplicationService.GetVacancyApplications:input_type -> application.GetVacancyApplicationsRequest
	7,  // 5: application.ApplicationService.UpdateStatus:input_type -> application.UpdateStatusRequest
	8,  // 6: application.ApplicationService.Withdraw:input_type -> application.WithdrawRequest
	0,  // 7: application.ApplicationService.GetApplicationStats:input_type -> application.AppStatsEmpty
	3,  // 8: application.ApplicationService.Apply:output_type -> application.ApplicationMessage
	9,  // 9: application.ApplicationService.GetMyApplications:output_type -> application.ApplicationsResponse
	9,  // 10: application.ApplicationService.GetVacancyApplications:output_type -> application.ApplicationsResponse
	3,  // 11: application.ApplicationService.UpdateStatus:output_type -> application.ApplicationMessage
	10, // 12: application.ApplicationService.Withdraw:output_type -> application.DeleteResponse
	2,  // 13: application.ApplicationService.GetApplicationStats:output_type -> application.ApplicationStatsResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_application_proto_init() }
func file_application_proto_init() {
	if File_application_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_application_proto_rawDesc), len(file_application_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_application_proto_goTypes,
		DependencyIndexes: file_application_proto_depIdxs,
		MessageInfos:      file_application_proto_msgTypes,
	}.Build()
	File_application_proto = out.File
	file_application_proto_goTypes = nil
	file_application_proto_depIdxs = nil
}
