// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: student.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatsEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsEmpty) Reset() {
	*x = StatsEmpty{}
	mi := &file_student_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsEmpty) ProtoMessage() {}

func (x *StatsEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsEmpty.ProtoReflect.Descriptor instead.
func (*StatsEmpty) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{0}
}

type SpecializationCount struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Specialization string                 `protobuf:"bytes,1,opt,name=specialization,proto3" json:"specialization,omitempty"`
	Count          int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpecializationCount) Reset() {
	*x = SpecializationCount{}
	mi := &file_student_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecializationCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecializationCount) ProtoMessage() {}

func (x *SpecializationCount) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecializationCount.ProtoReflect.Descriptor instead.
func (*SpecializationCount) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{1}
}

func (x *SpecializationCount) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *SpecializationCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StudentStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Total            int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	BySpecialization []*SpecializationCount `protobuf:"bytes,2,rep,name=by_specialization,json=bySpecialization,proto3" json:"by_specialization,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StudentStatsResponse) Reset() {
	*x = StudentStatsResponse{}
	mi := &file_student_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentStatsResponse) ProtoMessage() {}

func (x *StudentStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentStatsResponse.ProtoReflect.Descriptor instead.
func (*StudentStatsResponse) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{2}
}

func (x *StudentStatsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *StudentStatsResponse) GetBySpecialization() []*SpecializationCount {
	if x != nil {
		return x.BySpecialization
	}
	return nil
}

type CreateProfileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName      string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Iin            string                 `protobuf:"bytes,4,opt,name=iin,proto3" json:"iin,omitempty"`
	UniversityId   string                 `protobuf:"bytes,5,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	Skills         string                 `protobuf:"bytes,6,opt,name=skills,proto3" json:"skills,omitempty"`
	Gpa            float64                `protobuf:"fixed64,7,opt,name=gpa,proto3" json:"gpa,omitempty"`
	Specialization string                 `protobuf:"bytes,8,opt,name=specialization,proto3" json:"specialization,omitempty"`
	GraduationYear int32                  `protobuf:"varint,9,opt,name=graduation_year,json=graduationYear,proto3" json:"graduation_year,omitempty"`
	Bio            string                 `protobuf:"bytes,10,opt,name=bio,proto3" json:"bio,omitempty"`
	Phone          string                 `protobuf:"bytes,11,opt,name=phone,proto3" json:"phone,omitempty"`
	LocationCity   string                 `protobuf:"bytes,12,opt,name=location_city,json=locationCity,proto3" json:"location_city,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_student_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateProfileRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateProfileRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateProfileRequest) GetIin() string {
	if x != nil {
		return x.Iin
	}
	return ""
}

func (x *CreateProfileRequest) GetUniversityId() string {
	if x != nil {
		return x.UniversityId
	}
	return ""
}

func (x *CreateProfileRequest) GetSkills() string {
	if x != nil {
		return x.Skills
	}
	return ""
}

func (x *CreateProfileRequest) GetGpa() float64 {
	if x != nil {
		return x.Gpa
	}
	return 0
}

func (x *CreateProfileRequest) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *CreateProfileRequest) GetGraduationYear() int32 {
	if x != nil {
		return x.GraduationYear
	}
	return 0
}

func (x *CreateProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *CreateProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateProfileRequest) GetLocationCity() string {
	if x != nil {
		return x.LocationCity
	}
	return ""
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_student_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{4}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDRequest) Reset() {
	*x = GetByIDRequest{}
	mi := &file_student_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDRequest) ProtoMessage() {}

func (x *GetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{5}
}

func (x *GetByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateProfileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName      string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	UniversityId   string                 `protobuf:"bytes,4,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	Skills         string                 `protobuf:"bytes,5,opt,name=skills,proto3" json:"skills,omitempty"`
	Gpa            float64                `protobuf:"fixed64,6,opt,name=gpa,proto3" json:"gpa,omitempty"`
	Specialization string                 `protobuf:"bytes,7,opt,name=specialization,proto3" json:"specialization,omitempty"`
	GraduationYear int32                  `protobuf:"varint,8,opt,name=graduation_year,json=graduationYear,proto3" json:"graduation_year,omitempty"`
	Bio            string                 `protobuf:"bytes,9,opt,name=bio,proto3" json:"bio,omitempty"`
	Phone          string                 `protobuf:"bytes,10,opt,name=phone,proto3" json:"phone,omitempty"`
	LocationCity   string                 `protobuf:"bytes,11,opt,name=location_city,json=locationCity,proto3" json:"location_city,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_student_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateProfileRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateProfileRequest) GetUniversityId() string {
	if x != nil {
		return x.UniversityId
	}
	return ""
}

func (x *UpdateProfileRequest) GetSkills() string {
	if x != nil {
		return x.Skills
	}
	return ""
}

func (x *UpdateProfileRequest) GetGpa() float64 {
	if x != nil {
		return x.Gpa
	}
	return 0
}

func (x *UpdateProfileRequest) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *UpdateProfileRequest) GetGraduationYear() int32 {
	if x != nil {
		return x.GraduationYear
	}
	return 0
}

func (x *UpdateProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateProfileRequest) GetLocationCity() string {
	if x != nil {
		return x.LocationCity
	}
	return ""
}

type StudentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName      string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Iin            string                 `protobuf:"bytes,5,opt,name=iin,proto3" json:"iin,omitempty"`
	UniversityId   string                 `protobuf:"bytes,6,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Skills         string                 `protobuf:"bytes,9,opt,name=skills,proto3" json:"skills,omitempty"`
	Gpa            float64                `protobuf:"fixed64,10,opt,name=gpa,proto3" json:"gpa,omitempty"`
	Specialization string                 `protobuf:"bytes,11,opt,name=specialization,proto3" json:"specialization,omitempty"`
	GraduationYear int32                  `protobuf:"varint,12,opt,name=graduation_year,json=graduationYear,proto3" json:"graduation_year,omitempty"`
	Bio            string                 `protobuf:"bytes,13,opt,name=bio,proto3" json:"bio,omitempty"`
	Phone          string                 `protobuf:"bytes,14,opt,name=phone,proto3" json:"phone,omitempty"`
	LocationCity   string                 `protobuf:"bytes,15,opt,name=location_city,json=locationCity,proto3" json:"location_city,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StudentResponse) Reset() {
	*x = StudentResponse{}
	mi := &file_student_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentResponse) ProtoMessage() {}

func (x *StudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentResponse.ProtoReflect.Descriptor instead.
func (*StudentResponse) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{7}
}

func (x *StudentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StudentResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StudentResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *StudentResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *StudentResponse) GetIin() string {
	if x != nil {
		return x.Iin
	}
	return ""
}

func (x *StudentResponse) GetUniversityId() string {
	if x != nil {
		return x.UniversityId
	}
	return ""
}

func (x *StudentResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *StudentResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *StudentResponse) GetSkills() string {
	if x != nil {
		return x.Skills
	}
	return ""
}

func (x *StudentResponse) GetGpa() float64 {
	if x != nil {
		return x.Gpa
	}
	return 0
}

func (x *StudentResponse) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *StudentResponse) GetGraduationYear() int32 {
	if x != nil {
		return x.GraduationYear
	}
	return 0
}

func (x *StudentResponse) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *StudentResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *StudentResponse) GetLocationCity() string {
	if x != nil {
		return x.LocationCity
	}
	return ""
}

var File_student_proto protoreflect.FileDescriptor

const file_student_proto_rawDesc = "" +
	"\n" +
	"\rstudent.proto\x12\astudent\"\f\n" +
	"\n" +
	"StatsEmpty\"S\n" +
	"\x13SpecializationCount\x12&\n" +
	"\x0especialization\x18\x01 \x01(\tR\x0especialization\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"w\n" +
	"\x14StudentStatsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12I\n" +
	"\x11by_specialization\x18\x02 \x03(\v2\x1c.student.SpecializationCountR\x10bySpecialization\"\xea\x02\n" +
	"\x14CreateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x10\n" +
	"\x03iin\x18\x04 \x01(\tR\x03iin\x12#\n" +
	"\runiversity_id\x18\x05 \x01(\tR\funiversityId\x12\x16\n" +
	"\x06skills\x18\x06 \x01(\tR\x06skills\x12\x10\n" +
	"\x03gpa\x18\a \x01(\x01R\x03gpa\x12&\n" +
	"\x0especialization\x18\b \x01(\tR\x0especialization\x12'\n" +
	"\x0fgraduation_year\x18\t \x01(\x05R\x0egraduationYear\x12\x10\n" +
	"\x03bio\x18\n" +
	" \x01(\tR\x03bio\x12\x14\n" +
	"\x05phone\x18\v \x01(\tR\x05phone\x12#\n" +
	"\rlocation_city\x18\f \x01(\tR\flocationCity\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\" \n" +
	"\x0eGetByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd8\x02\n" +
	"\x14UpdateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12#\n" +
	"\runiversity_id\x18\x04 \x01(\tR\funiversityId\x12\x16\n" +
	"\x06skills\x18\x05 \x01(\tR\x06skills\x12\x10\n" +
	"\x03gpa\x18\x06 \x01(\x01R\x03gpa\x12&\n" +
	"\x0especialization\x18\a \x01(\tR\x0especialization\x12'\n" +
	"\x0fgraduation_year\x18\b \x01(\x05R\x0egraduationYear\x12\x10\n" +
	"\x03bio\x18\t \x01(\tR\x03bio\x12\x14\n" +
	"\x05phone\x18\n" +
	" \x01(\tR\x05phone\x12#\n" +
	"\rlocation_city\x18\v \x01(\tR\flocationCity\"\xb3\x03\n" +
	"\x0fStudentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x10\n" +
	"\x03iin\x18\x05 \x01(\tR\x03iin\x12#\n" +
	"\runiversity_id\x18\x06 \x01(\tR\funiversityId\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\x16\n" +
	"\x06skills\x18\t \x01(\tR\x06skills\x12\x10\n" +
	"\x03gpa\x18\n" +
	" \x01(\x01R\x03gpa\x12&\n" +
	"\x0especialization\x18\v \x01(\tR\x0especialization\x12'\n" +
	"\x0fgraduation_year\x18\f \x01(\x05R\x0egraduationYear\x12\x10\n" +
	"\x03bio\x18\r \x01(\tR\x03bio\x12\x14\n" +
	"\x05phone\x18\x0e \x01(\tR\x05phone\x12#\n" +
	"\rlocation_city\x18\x0f \x01(\tR\flocationCity2\xed\x02\n" +
	"\x0eStudentService\x12H\n" +
	"\rCreateProfile\x12\x1d.student.CreateProfileRequest\x1a\x18.student.StudentResponse\x12B\n" +
	"\n" +
	"GetProfile\x12\x1a.student.GetProfileRequest\x1a\x18.student.StudentResponse\x12<\n" +
	"\aGetByID\x12\x17.student.GetByIDRequest\x1a\x18.student.StudentResponse\x12H\n" +
	"\rUpdateProfile\x12\x1d.student.UpdateProfileRequest\x1a\x18.student.StudentResponse\x12E\n" +
	"\x0fGetStudentStats\x12\x13.student.StatsEmpty\x1a\x1d.student.StudentStatsResponseB%Z#student-service/internal/grpc/pb;pbb\x06proto3"

var (
	file_student_proto_rawDescOnce sync.Once
	file_student_proto_rawDescData []byte
)

func file_student_proto_rawDescGZIP() []byte {
	file_student_proto_rawDescOnce.Do(func() {
		file_student_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_student_proto_rawDesc), len(file_student_proto_rawDesc)))
	})
	return file_student_proto_rawDescData
}

var file_student_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_student_proto_goTypes = []any{
	(*StatsEmpty)(nil),           // 0: student.StatsEmpty
	(*SpecializationCount)(nil),  // 1: student.SpecializationCount
	(*StudentStatsResponse)(nil), // 2: student.StudentStatsResponse
	(*CreateProfileRequest)(nil), // 3: student.CreateProfileRequest
	(*GetProfileRequest)(nil),    // 4: student.GetProfileRequest
	(*GetByIDRequest)(nil),       // 5: student.GetByIDRequest
	(*UpdateProfileRequest)(nil), // 6: student.UpdateProfileRequest
	(*StudentResponse)(nil),      // 7: student.StudentResponse
}
var file_student_proto_depIdxs = []int32{
	1, // 0: student.StudentStatsResponse.by_specialization:type_name -> student.SpecializationCount
	3, // 1: student.StudentService.CreateProfile:input_type -> student.CreateProfileRequest
	4, // 2: student.StudentService.GetProfile:input_type -> student.GetProfileRequest
	5, // 3: student.StudentService.GetByID:input_type -> student.GetByIDRequest
	6, // 4: student.StudentService.UpdateProfile:input_type -> student.UpdateProfileRequest
	0, // 5: student.StudentService.GetStudentStats:input_type -> student.StatsEmpty
	7, // 6: student.StudentService.CreateProfile:output_type -> student.StudentResponse
	7, // 7: student.StudentService.GetProfile:output_type -> student.StudentResponse
	7, // 8: student.StudentService.GetByID:output_type -> student.StudentResponse
	7, // 9: student.StudentService.UpdateProfile:output_type -> student.StudentResponse
	2, // 10: student.StudentService.GetStudentStats:output_type -> student.StudentStatsResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_student_proto_init() }
func file_student_proto_init() {
	if File_student_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_student_proto_rawDesc), len(file_student_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_student_proto_goTypes,
		DependencyIndexes: file_student_proto_depIdxs,
		MessageInfos:      file_student_proto_msgTypes,
	}.Build()
	File_student_proto = out.File
	file_student_proto_goTypes = nil
	file_student_proto_depIdxs = nil
}
